global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'monitoring_pi'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'cadvisor'
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'proxmox_nodes'
  file_sd_configs:
  - files:
    - '/etc/prometheus/targets.json'
    refresh_interval: 1m
